# run_cram_depth_pipeline.sh
#
# This script counts reads and computes read-depth profiles from CRAM files
# listed in a manifest. It wraps the pipeline's compiled binaries and
# adds friendly CLI, dependency checks, safer temporary directory handling,
# and helpful usage information.

set -euo pipefail

usage() {
    cat <<-USAGE
Usage: $0 -m MANIFEST -o OUT_DIR -n OUT_NAME [options]

Required:
  -m, --manifest   Path to CRAM manifest (tab/space-separated: ID CRAM_PATH)
  -o, --out-dir    Output directory
  -n, --out-name   Output prefix/name for produced files

Options:
  -t, --tmp-dir    Temporary directory (default: autogenerated in /tmp)
  -j, --cores      Number of cores for parallel processing (default: nproc)
  -k, --keep-tmp   Keep tmp dir after successful run
  -v, --verbose    Enable verbose output
  -h, --help       Show this message

Example:
  $0 -m crams.manifest -o results -n cohortA
USAGE
}

# Default flags
TMP_DIR=""
CORES=$(nproc)
KEEP_TMP=false
VERBOSE=false

# Parse arguments (supports long options)
while [[ $# -gt 0 ]]; do
    case "$1" in
        -m|--manifest)
            CRAM_MANIFEST="$2"; shift 2;;
        -o|--out-dir)
            OUT_DIR="$2"; shift 2;;
        -n|--out-name)
            OUT_NAME="$2"; shift 2;;
        -t|--tmp-dir)
            TMP_DIR="$2"; shift 2;;
        -j|--cores)
            CORES="$2"; shift 2;;
        -k|--keep-tmp)
            KEEP_TMP=true; shift 1;;
        -v|--verbose)
            VERBOSE=true; shift 1;;
        -h|--help)
            usage; exit 0;;
        *)
            echo "Unknown option: $1" >&2; usage; exit 1;;
    esac
done

# Validate required args
: "${OUT_DIR:?OUT_DIR is not set (use -o/--out-dir)}"
: "${OUT_NAME:?OUT_NAME is not set (use -n/--out-name)}"
: "${CRAM_MANIFEST:?CRAM_MANIFEST is not set (use -m/--manifest)}"

echo "$(date): performing depth profiling for cram files in $CRAM_MANIFEST"
OUT_PREFIX=$OUT_DIR/$OUT_NAME
mkdir -p "$OUT_DIR"
echo "$(date): saving outputs to $OUT_PREFIX"

# Setup TMP_DIR: use user-specified or create a unique temp dir under /tmp
if [[ -z "$TMP_DIR" ]]; then
    TMP_DIR=$(mktemp -d /tmp/run_cram_depth_pipeline.XXXXXX)
    CLEAN_TMP=true
else
    TMP_DIR=$TMP_DIR/$OUT_NAME
    mkdir -p "$TMP_DIR"
    CLEAN_TMP=false
fi
if $VERBOSE; then
    echo "$(date): using TMP_DIR=$TMP_DIR"
fi

trap_to_cleanup() {
    local exit_code=$?
    if [[ $exit_code -ne 0 ]]; then
        echo "$(date): script exited with code $exit_code. Temporary dir: $TMP_DIR" >&2
        echo "You can inspect it and re-run or set --keep-tmp to preserve temp files." >&2
    else
        if $KEEP_TMP || [[ "$CLEAN_TMP" == false ]]; then
            echo "$(date): preserving tmp dir: $TMP_DIR"
        else
            rm -rf "$TMP_DIR"
            if $VERBOSE; then echo "$(date): removed tmp dir"; fi
        fi
    fi
}
trap trap_to_cleanup EXIT

echo "$(date): downloading GRCh38 GC masks"
GC_MASKS=$TMP_DIR/GRCh38.GCmasks.bin
if command -v curl >/dev/null 2>&1; then
    curl -fsSLo "$GC_MASKS" https://data.broadinstitute.org/lohlab/mCAs_WGS/GRCh38.GCmasks.bin
elif command -v wget >/dev/null 2>&1; then
    wget -qO "$GC_MASKS" https://data.broadinstitute.org/lohlab/mCAs_WGS/GRCh38.GCmasks.bin
else
    echo "Error: curl or wget is required to download GC masks" >&2; exit 1
fi

# Check for required external commands early so users get clear errors
missing_cmds=()
for cmd in parallel pigz zip awk tr cat; do
    if ! command -v $cmd >/dev/null 2>&1; then
        missing_cmds+=("$cmd")
    fi
done
if [[ ${#missing_cmds[@]} -ne 0 ]]; then
    echo "Error: missing required commands: ${missing_cmds[*]}" >&2
    echo "Please install them (e.g. GNU parallel, pigz, zip) and re-run." >&2
    exit 1
fi

if $VERBOSE; then echo "$(date): dependencies present"; fi
cat_cram_file() {
    CRAM_FILE="$1"
    if [[ "$CRAM_FILE" == s3:* ]]; then 
        aws s3 cp --no-sign-request "$CRAM_FILE" - 2> /dev/null
    elif [[ ( "$CRAM_FILE" == ftp:* ) || ( "$CRAM_FILE" == http:* ) || ( "$CRAM_FILE" == https:* ) ]]; then 
        curl -L -o - $CRAM_FILE 2> /dev/null
    else
        cat "$CRAM_FILE"
    fi
}

run_count_reads() {
    ID=$1
    TMP_DIR=$2
    CRAM_FILE=$3
    ../bin/countReadsSaveDiscordant \
        "$ID" \
        <( cat_cram_file $CRAM_FILE ) \
        "$GC_MASKS" \
        1000 \
        "$TMP_DIR/$ID" \
        > /dev/null
}
export -f cat_cram_file
export -f run_count_reads

# count reads in each cram file
echo "$(date): counting reads in the cram files"
set +e # OK if some jobs fail; status will appear in job log
cat "$CRAM_MANIFEST" | tr '\t' ' '  \
    | parallel --joblog /dev/stderr --colsep ' ' --retries 4 --jobs $CORES GC_MASKS=$GC_MASKS run_count_reads {1} $TMP_DIR {2}
set -e

# compute 20kb and 50kb read-depth profiles (and CNV calls) simultaneously
for RES_KB in 20 50
do
    echo "$(date): computing $RES_KB kb depth profiles (and calling CNVs)"
    ../bin/computeDepthProfiles \
        <(cat $TMP_DIR/*.counts.bin.bgz) \
        "$GC_MASKS" \
        ${RES_KB}e3 \
        "$TMP_DIR/${RES_KB}kb"
    pigz -c "$TMP_DIR/${RES_KB}kb.profiles.txt" > "$OUT_PREFIX.${RES_KB}kb_profiles.txt.gz"
    pigz -c "$TMP_DIR/${RES_KB}kb.CNVs.txt" > "$OUT_PREFIX.CNVs.txt.gz"
done

# collate GC profiles
cat $TMP_DIR/*.GCprofile.txt > $OUT_PREFIX.GCprofiles.txt

# collate discordant reads
cat $TMP_DIR/*.discordant.txt | pigz > $OUT_PREFIX.discordant.txt.gz

# collate 1kb-bin read counts into archive
zip -0 -j $OUT_PREFIX.counts.zip $TMP_DIR/*.counts.bin.bgz

wc -l $OUT_PREFIX.GCprofiles.txt \
    | awk '{printf("Counted reads and created depth profiles for %d ",$1)}'
wc -l $CRAM_MANIFEST \
    | awk '{printf(" of %d cram files\n",$1)}'
