
# Friendly wrapper for calling mCAs on a chromosome
# improves usability: adds CLI, dependency checks, safer TMP handling,
# and dry-run/verbose flags while preserving existing logic.

set -euo pipefail

usage() {
    cat <<-USAGE
Usage: $0 -m MANIFEST -o OUT_DIR -c CHR --depth-dir DEPTH_DIR --ref-bias REF_BIAS \
          --genome-blacklist GENOME_BLACKLIST --pc-dir PC_DIR --ref-file REF_FILE --phased-bcf PHASED_BCF [options]

Required:
  -m, --manifest            Path to CRAM manifest (ID CRAM_PATH)
  -o, --out-dir             Output directory
  -c, --chr                 Chromosome to process (e.g. chr1)
  -n, --name                Name prefix of files in the depth directory
  --depth-dir               Directory containing outputs of the depth pipeline
  --ref-bias                File with read mapping REF bias
  --genome-blacklist        Genome blacklist file
  --pc-dir                  Directory containing PC adjustment files
  --ref-file                Path to reference fasta
  --phased-bcf              Input phased BCF

Options:
  -t, --tmp-dir             Temporary directory (default autogenerated)
  -j, --cores               Number of cores for parallel processing (default: nproc)
  -k, --keep-tmp            Keep tmp dir after success
  -v, --verbose             Verbose output
  -h, --help                Show this message

Example:
  $0 -m crams.manifest -o results -c chr1 --depth-dir depth_out --ref-bias ref_bias.txt \
      --genome-blacklist blacklist.bed --pc-dir pc_dir --ref-file ref.fa --phased-bcf phased.bcf
USAGE
}

# Defaults
TMP_DIR=""
CORES=$(nproc)
KEEP_TMP=false
VERBOSE=false

# Parse args
while [[ $# -gt 0 ]]; do
    case "$1" in
        -m|--manifest) CRAM_MANIFEST="$2"; shift 2;;
        -o|--out-dir) OUT_DIR="$2"; shift 2;;
        -c|--chr) CHR="$2"; shift 2;;
        -n|--name) PFX="$2"; shift 2;;
        --depth-dir) DEPTH_DIR="$2"; shift 2;;
        --ref-bias) REF_BIAS="$2"; shift 2;;
        --genome-blacklist) GENOME_BLACKLIST="$2"; shift 2;;
        --pc-dir) PC_DIR="$2"; shift 2;;
        --ref-file) REF_FILE="$2"; shift 2;;
        --phased-bcf) PHASED_BCF="$2"; shift 2;;
        -t|--tmp-dir) TMP_DIR="$2"; shift 2;;
        -j|--cores) CORES="$2"; shift 2;;
        -k|--keep-tmp) KEEP_TMP=true; shift 1;;
        -v|--verbose) VERBOSE=true; shift 1;;
        -h|--help) usage; exit 0;;
        *) echo "Unknown option $1" >&2; usage; exit 1;;
    esac
done

# Validate required args
: "${OUT_DIR:?OUT_DIR is not set (use -o/--out-dir)}"
: "${CRAM_MANIFEST:?CRAM_MANIFEST is not set (use -m/--manifest)}"
: "${CHR:?CHR is not set (use -c/--chr)}"
: "${PFX:?PFX is not set (use -n/--name)}"
: "${DEPTH_DIR:?DEPTH_DIR is not set (use --depth-dir)}"
: "${REF_BIAS:?REF_BIAS is not set (use --ref-bias)}"
: "${GENOME_BLACKLIST:?GENOME_BLACKLIST is not set (use --genome-blacklist)}"
: "${PC_DIR:?PC_DIR is not set (use --pc-dir)}"
: "${REF_FILE:?REF_FILE is not set (use --ref-file)}"
: "${PHASED_BCF:?PHASED_BCF is not set (use --phased-bcf)}"

mkdir -p "$OUT_DIR"

# Setup TMP_DIR
if [[ -z "$TMP_DIR" ]]; then
    TMP_DIR=$(mktemp -d /tmp/run_call_mCAs_pipeline.XXXXXX)
    CLEAN_TMP=true
else
    mkdir -p "$TMP_DIR"
    CLEAN_TMP=false
fi
if $VERBOSE; then echo "$(date): using TMP_DIR=$TMP_DIR"; fi

trap_to_cleanup() {
    local exit_code=$?
    if [[ $exit_code -ne 0 ]]; then
        echo "$(date): script exited with code $exit_code. Temporary dir: $TMP_DIR" >&2
    else
        if $KEEP_TMP || [[ "$CLEAN_TMP" == false ]]; then
            echo "$(date): preserving tmp dir: $TMP_DIR"
        else
            rm -rf "$TMP_DIR"
            if $VERBOSE; then echo "$(date): removed tmp dir"; fi
        fi
    fi
}
trap trap_to_cleanup EXIT

# Check dependencies
missing=()
for cmd in bcftools parallel awk zcat grep cut cat egrep; do
    if ! command -v $cmd >/dev/null 2>&1; then
        missing+=("$cmd")
    fi
done
if [[ ${#missing[@]} -ne 0 ]]; then
    echo "Error: missing required commands: ${missing[*]}" >&2
    exit 1
fi

echo "$(date): filtering $PHASED_BCF bcf to MAF>0.01 on $CHR"
PHASED_BCF_COMMON=$TMP_DIR/${PFX}.$CHR.common.phased.bcf
bcftools view "$PHASED_BCF" -r "$CHR" -Ob -S <(awk '{print $1}' "$CRAM_MANIFEST") > "$PHASED_BCF_COMMON"
bcftools index -f "$PHASED_BCF_COMMON"

echo "$(date): extracting $CHR allelic depths for files in $CRAM_MANIFEST"
cat "$CRAM_MANIFEST" | tr '\t' ' ' \
    | parallel --halt-on-error 2 --colsep ' ' --joblog /dev/stderr --retries 4 --jobs $CORES \
        "TMP_DIR=$TMP_DIR bash ../tools/extract_cram_AD.sh {1} $CHR $PHASED_BCF_COMMON $REF_FILE {2} | cut -f-6 > ${TMP_DIR}/$CHR.ADs.{1}.txt"

echo "$(date): writing bcf with allelic depths"
AD_BCF=$TMP_DIR/${PFX}.$CHR.common.phased.AD.bcf
../bin/mCAs_WGS prepare-bcf \
    --clear-ADs \
    --write-ADs \
    --het-format-str "${TMP_DIR}/${CHR}.ADs.%s.txt" \
    < "$PHASED_BCF_COMMON" \
    > "$AD_BCF"
bcftools index -f "$AD_BCF"
rm ${TMP_DIR}/$CHR.ADs.*.txt

echo "$(date): calling mCAs on $CHR"
zcat "${DEPTH_DIR}/${PFX}.CNVs.txt.gz" \
    | grep -v MEDIAN \
    | grep -w "$CHR" \
    | cut -f1-5 \
    | cat - <(awk -v CHR=$CHR '$1==CHR {print "BLACKLIST\t"$0"\tMASK"}' "$GENOME_BLACKLIST") \
    > "$TMP_DIR/$PFX.$CHR.CNVs.txt"

zgrep -w "$CHR" "$REF_BIAS" > "$TMP_DIR/$CHR.ref_bias.txt"

../bin/mCAs_WGS make-calls \
    --cnv-mask "$TMP_DIR/$PFX.$CHR.CNVs.txt" \
    --ref-bias "$TMP_DIR/$CHR.ref_bias.txt" \
    --calls-out "$TMP_DIR/$PFX.$CHR.calls.no_depth.txt" \
    --bcf-out "$OUT_DIR/$PFX.$CHR.allelic_shift.bcf" \
    --phred-phase-switch 20 \
    --bcf "$AD_BCF"

bcftools index -f "$OUT_DIR/$PFX.$CHR.allelic_shift.bcf"

awk -v OFS='\t' 'FNR!=1 {print $1,$3":"$4"-"$5}' ${TMP_DIR}/${PFX}.$CHR.calls.no_depth.txt > ${TMP_DIR}/${PFX}.$CHR.ID_region_list.txt
if [ ! -s ${TMP_DIR}/${PFX}.$CHR.ID_region_list.txt ]; then
    echo "$(date): finished with no calls"
    mv ${TMP_DIR}/${PFX}.$CHR.calls.no_depth.txt ${OUT_DIR}/${PFX}.$CHR.calls.txt
    exit 0
fi

echo "$(date): downloading GRCh38 GC masks"
GC_MASKS=$TMP_DIR/GRCh38.GCmasks.bin
if command -v curl >/dev/null 2>&1; then
    curl -fsSLo "$GC_MASKS" https://data.broadinstitute.org/lohlab/mCAs_WGS/GRCh38.GCmasks.bin
elif command -v wget >/dev/null 2>&1; then
    wget -qO "$GC_MASKS" https://data.broadinstitute.org/lohlab/mCAs_WGS/GRCh38.GCmasks.bin
else
    echo "Error: curl or wget is required to download GC masks" >&2; exit 1
fi

echo "$(date): extracting depth for mCA calls on $CHR"
ID_REGION_LIST=${TMP_DIR}/${PFX}.$CHR.ID_region_list.txt \
OUT_FILE=${TMP_DIR}/${PFX}.$CHR.depth.txt \
PC_DIR=$PC_DIR \
DEPTH_DIR=$DEPTH_DIR \
TMP_DIR=$TMP_DIR \
GC_MASKS=$GC_MASKS \
PFX=$PFX \
    bash ../tools/compute_region_depth_PCadj.sh

zcat ${DEPTH_DIR}/${PFX}.CNVs.txt.gz \
    | grep MEDIAN \
    | egrep 'chrX|chrY' \
    | awk '
$2=="chrX" {xploidy[$1]=$6}
$2=="chrY" {yploidy[$1]=$6}
END {
    for (ID in xploidy) {
        if (xploidy[ID]+0 == 2 && yploidy[ID]+0 == 0) print ID,"F";
        else if (xploidy[ID]+0 == 1 && yploidy[ID]+0 == 1) print ID,"M";
        else print ID,"U"
    }
}' > $TMP_DIR/$PFX.sex.txt

awk -v OFS='\t' '
ARGIND==1 && FNR==1 { for (i=1; i<=NF; i++) f1[$i]=i; }
ARGIND==1 && FNR>1 {
    ID=$(f1["ID"]);
    chrStr=$(f1["chr"]);
    bpStart=$(f1["bpStart"]);
    bpEnd=$(f1["bpEnd"]);

    depth[ID,chrStr,bpStart,bpEnd]=$5; 
    depth_se[ID,chrStr,bpStart,bpEnd]=$6
} 
ARGIND==2 { 
    sex[$1] = $2;
}
ARGIND==3 && FNR==1 { 
    for (i=1; i<=NF; i++) f3[$i]=i; 
    print $0;
}
ARGIND==3 && FNR>1 {
    ID=$(f3["ID"]);
    chrStr=$(f3["chr"]);
    bpStart=$(f3["bpStart"]);
    bpEnd=$(f3["bpEnd"]);

    $(f3["sex"])=(ID in sex) ? sex[ID] : "U"; 
    $(f3["depth"])=depth[ID,chrStr,bpStart,bpEnd]; 
    $(f3["depthSE"])=depth_se[ID,chrStr,bpStart,bpEnd]; 
    print $0
}' \
    ${TMP_DIR}/${PFX}.$CHR.depth.txt \
    ${TMP_DIR}/${PFX}.sex.txt \
    ${TMP_DIR}/${PFX}.$CHR.calls.no_depth.txt  \
    > ${OUT_DIR}/${PFX}.$CHR.calls.txt 

rm $TMP_DIR/$PFX.sex.txt

echo "$(date): finished analysis"
