// compiling on RAP (to get libcurl + dependencies):
// sudo apt --yes install libdeflate-dev # (to get libdeflate headers)
// tar -zxf /mnt/project/lohdata/resources/htslib/htslib-1.18-libdeflate.tar.gz -C .
// g++ -O3 -Wall ComputeRegionDepthsPCadj.cpp -o computeRegionDepthsPCadj -Ihtslib-1.18-libdeflate/ htslib-1.18-libdeflate/libhts.a -lcurl -ldeflate -lz -lpthread

// compiling on O2 (without curl):
// g++ -O3 -Wall ComputeRegionDepthsPCadj.cpp -o computeRegionDepthsPCadj -I/n/data1/bwh/medicine/loh/ploh/external_software/htslib/htslib-1.18/ -L/n/data1/bwh/medicine/loh/ploh/external_software/htslib/htslib-1.18/ -L/n/data1/bwh/medicine/loh/ploh/external_software/libdeflate-1.18/ -Wl,-Bstatic -lhts -ldeflate -Wl,-Bdynamic -lz -lpthread

#include <iostream>
#include <iomanip>
#include <fstream>
#include <sstream>
#include <vector>
#include <string>
#include <map>
#include <utility>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cassert>
#include <cmath>
#include <sys/time.h>
#include <htslib/kstring.h>
#include <htslib/bgzf.h>

#include "RefMasks.hpp"
#include "RegionDepthUtils.cpp"

using namespace std;

void readCountsBinHeader(BGZF *finCounts, const string &IDstrCheck, uint16_t &masks,
			 vector <float> &GCprofile, int &binSize) {
  int IDlen;
  assert(bgzf_read(finCounts, &IDlen, sizeof(IDlen)) == sizeof(IDlen));
  char IDstr[IDlen+1]; assert(bgzf_read(finCounts, IDstr, IDlen) > 0); IDstr[IDlen] = '\0';
  assert(IDstr == IDstrCheck);
  assert(bgzf_read(finCounts, &masks, sizeof(masks)) > 0); // masks used
  assert(bgzf_read(finCounts, &GCprofile[0], sizeof(GCprofile[0])*GCprofile.size()) > 0);
  assert(bgzf_read(finCounts, &binSize, sizeof(binSize)) > 0);
}

int main(int argc, char *argv[]){

  if (argc != 11) {
    fprintf(stderr, "Usage:\n");
    fprintf(stderr, "- arg1 = ID region list file\n");
    fprintf(stderr, "- arg2 = CNVs file (generated by ComputeDepthProfiles.cpp)\n");
    fprintf(stderr, "- arg3 = depth profile file (generated by ComputeDepthProfiles.cpp)\n");
    fprintf(stderr, "- arg4 = PCs+baselines file prefix -> {.isMale{0,1}.{PCs,baselines}.txt\n");
    fprintf(stderr, "- arg5 = binary file containing precomputed GC content and masks\n");
    fprintf(stderr, "- arg6 = path to bin-count files (generated by CountReads.cpp)\n");
    fprintf(stderr, "         (e.g., /path/to/%%s.counts.bin.bgz [%%s to be replaced with ID])\n");
    fprintf(stderr, "- arg7 = crop value to use in computing read-depth PC coeffs (e.g., 0.08)\n");
    fprintf(stderr, "- arg8 = number of PCs to use\n");
    fprintf(stderr, "- arg9 = output file for region-level PC-adjusted depth\n");
    fprintf(stderr, "- arg10 = output file for bin-level PC-adjusted data (/dev/null to skip)\n");
    exit(1);
  }

  struct timeval tv;
  gettimeofday(&tv, NULL); double tPrev = tv.tv_sec + tv.tv_usec*1e-6;

  const char *IDregionFile = argv[1];
  const char *CNVsFile = argv[2];
  const char *depthProfileFile = argv[3];
  const char *PCbaselinesPrefix = argv[4];
  const char *GCmasksFile = argv[5];
  const char *binCountFmtStr = argv[6];
  double readDepthRelCrop = 0;
  sscanf(argv[7], "%lf", &readDepthRelCrop); assert(readDepthRelCrop > 0);
  int numPCs; sscanf(argv[8], "%d", &numPCs);
  const char *outFile = argv[9];
  const char *outFileBinLevel = argv[10];
  bool writeBinLevelOutput = strcmp(outFileBinLevel, "/dev/null");

  // load precomputed GC content and masks
  cerr << "Loading precomputed GC content and masks: " << GCmasksFile << endl;
  int shift; // bit shift
  vector <int> chrLens(NUM_CHROMS); // chromosome lengths
  vector < vector <uint16_t> > GCmasks(NUM_CHROMS); // GCmasks vectors
  readGCmasks(GCmasksFile, shift, chrLens, GCmasks);

  // load list of (ID, region) pairs for which to compute depth
  cerr << "Loading ID region pairs for which to compute depth: " << IDregionFile << endl;
  map <string, RegionsPerChr> IDregions;
  {
    ifstream finIDregions(IDregionFile); assert(IDregionFile);
    string IDstr, regionStr;
    int ctrPairs = 0;
    while (finIDregions >> IDstr >> regionStr) {
      int colonPos = regionStr.find(':');
      assert(colonPos != (int) string::npos);
      int chr0 = parseChrStrToChr0(regionStr.substr(0, colonPos).c_str());
      int start, end;
      assert(sscanf(regionStr.substr(colonPos+1).c_str(), "%d-%d", &start, &end) == 2);
      assert(start > 0);
      assert(end > start);
      IDregions[IDstr].regions[chr0].push_back(make_pair(start, end));
      ctrPairs++;
    }
    finIDregions.close();
    cerr << "Read " << ctrPairs << " (ID, region) pairs for " << IDregions.size()
	 << " unique samples" << endl;
    assert(!IDregions.empty());
  }

  // read CNVs and determine sex
  cerr << "Loading CNV calls to optionally mask: " << CNVsFile << endl;
  map <string, bool> IDisMale;
  map <string, RegionsPerChr> CNVs = readCNVsexData(IDisMale, CNVsFile);

  // read binSize and numBins per chr from bin-counts file for first ID
  int binSize;
  vector <int> chrBinToProfileInd[NUM_CHROMS]; // to be populated with indexes into profile lines
  {
    const string &firstIDstr = CNVs.begin()->first;
    char countsBinFile[strlen(binCountFmtStr) + firstIDstr.length()];
    sprintf(countsBinFile, binCountFmtStr, firstIDstr.c_str());
    cerr << "Reading bin size and bins per chrom: " << countsBinFile << endl;
    BGZF *finCounts = bgzf_open(countsBinFile, "r"); assert(finCounts!=NULL);
    uint16_t masks;
    vector <float> GCprofile(MAX_GC_PCT+1);
    readCountsBinHeader(finCounts, firstIDstr, masks, GCprofile, binSize);

    vector <uint16_t> readsPerBin; // buffer to store unzipped read counts
    for (int c0 = 0; c0 < NUM_CHROMS; c0++) {
      int numBins; assert(bgzf_read(finCounts, &numBins, sizeof(numBins)) > 0);
      chrBinToProfileInd[c0].resize(numBins);
      // read and throw away counts
      readsPerBin.resize(numBins);
      assert(bgzf_read(finCounts, &readsPerBin[0], numBins * sizeof(readsPerBin[0])) > 0);
    }
    bgzf_close(finCounts);
  }

  // read profile regions and baselines
  vector <ProfileRegion> profileRegions;
  vector <int> profileChrStartInds;
  vector <double> baselines[2]; // female, male
  profileRegions = readProfileRegionsBaselines(profileChrStartInds, baselines, chrBinToProfileInd,
					       binSize, PCbaselinesPrefix);
  int profileLen = profileRegions.size();

  // read genomic wave PCs
  vector < vector <double> > PCs[2];
  readGenomicWavePCs(PCs, PCbaselinesPrefix, numPCs, profileLen);

  // write output headers
  ofstream fout(outFile);
  fout << "ID" << "\t" << "chr" << "\t" << "bpStart" << "\t" << "bpEnd"
       << "\t" << "depthDev" << "\t" << "SE"
       << "\t" << "relDepthExclCNV" << "\t" << "relDepthInclCNV" << "\t" << "fracInCNV"
       << "\t" << "OBSinclCNV" << "\t" << "EXPinclCNV" << "\t" << "EXPinclCNVnoPC" 
       << "\t" << "OBSexclCNV" << "\t" << "EXPexclCNV" << "\t" << "EXPexclCNVnoPC" << endl;
  fout << fixed << setprecision(4);

  ofstream foutBinLevel(outFileBinLevel);
  foutBinLevel << "ID" << "\t" << "region" << "\t" << "bpStart" << "\t" << "bpEnd"
       << "\t" << "OBSreads" << "\t" << "EXPreads" << "\t" << "EXPreadsNoPCadj" 
       << "\t" << "relDepth" << "\t" << "inCNV" << endl;
  foutBinLevel << fixed << setprecision(4);

  // analyze depth profile file
  cerr << "Reading depth profiles: " << depthProfileFile << endl;
  {
    BGZF *finDepthProfile = bgzf_open(depthProfileFile, "r"); assert(finDepthProfile!=NULL);
    vector <double> depthProfile(profileLen);
    kstring_t kstr = KS_INITIALIZE;
    int line = 0, ctrIDsAnalyzed = 0, ctrIDregionsAnalyzed = 0;
    string IDstr;
    while (readProfileLine(IDstr, depthProfile, finDepthProfile, &IDregions, line==0, &kstr)) {
      line++;
      if (line == 1) continue; // skip header line
      if (IDstr.empty()) continue; // ID in line wasn't requested; skip

      ctrIDsAnalyzed++;

      bool sex = IDisMale[IDstr];

      // compute PC coeffs and combine to estimate genomic wave (after applying crop)
      vector <double> wave = computeGenomicWave(depthProfile, PCs[sex], baselines[sex],
						readDepthRelCrop);

      // compute final calibration (median of median-per-autosome)
      double medianAutosomeObsExp = computeMedianAutosomeObsExp(depthProfile, baselines[sex], wave, profileChrStartInds, true);
      double medianAutosomeObsExpNoPC = computeMedianAutosomeObsExp(depthProfile, baselines[sex], wave, profileChrStartInds, false);

      // read header of bin-count file
      char countsBinFile[strlen(binCountFmtStr) + IDstr.length()];
      sprintf(countsBinFile, binCountFmtStr, IDstr.c_str());
      BGZF *finCounts = bgzf_open(countsBinFile, "r"); assert(finCounts!=NULL);
      int binSizeCheck;
      uint16_t masks;
      vector <float> GCprofile(MAX_GC_PCT+1);
      readCountsBinHeader(finCounts, IDstr, masks, GCprofile, binSizeCheck);
      assert(binSize == binSizeCheck);

      vector <uint16_t> readsPerBin; // buffer to store unzipped read counts
      vector <double> expPerBin; // buffer to store expected read counts
      vector <double> expPerBinNoPCadj; // buffer to store expected read counts without PCadj
      vector <char> inCNV; // buffer to store expected read counts
      vector <double> cumOBSexclCNV, cumOBSinclCNV, cumEXPexclCNV, cumEXPinclCNV, cumEXPexclCNVnoPC, cumEXPinclCNVnoPC;
      for (int chr0 = 0; chr0 < NUM_CHROMS; chr0++) {
	// read OBS bin counts
	int numBins; assert(bgzf_read(finCounts, &numBins, sizeof(numBins)) > 0);
	assert(numBins == (int) chrBinToProfileInd[chr0].size());
	readsPerBin.resize(numBins);
	assert(bgzf_read(finCounts, &readsPerBin[0], numBins * sizeof(readsPerBin[0])) > 0);
	const RegionsPerChr &regionsPerChr = IDregions[IDstr];
	if (!regionsPerChr.regions[chr0].empty()) {
	  ctrIDregionsAnalyzed += regionsPerChr.regions[chr0].size();
	  // compute EXP reads per bin
	  expPerBin.resize(numBins);
      expPerBinNoPCadj.resize(numBins);
	  for (int b = 0; b < numBins; b++) {
	    // compute raw EXP based on just GCprofile and GCmasks
	    double expReads = 0;
	    int binStart = b*binSize;
	    int binEnd = min(binStart+binSize, chrLens[chr0]);
	    for (int posShift = binStart>>shift; (posShift<<shift) < binEnd; posShift++) {
	      uint16_t gcMasks = GCmasks[chr0][posShift];
	      if (!(gcMasks & masks)) // no mask bits set
		expReads += GCprofile[getGCpct(gcMasks)] *
		  (min(binEnd, (posShift+1)<<shift) - max(binStart, posShift<<shift));
	    }
	    // multiply in baseline value and wave adjustment (using lookup table to index)
	    int profileInd = chrBinToProfileInd[chr0][b];
        expPerBinNoPCadj[b] = expReads;
        expReads *= baselines[sex][profileInd];
	    //expPerBinNoPCadj[b] = expReads * medianAutosomeObsExpNoPC;
	    expPerBin[b] = expReads * (1+wave[profileInd]) * medianAutosomeObsExp;
	  }

	  // set up bin-level CNV mask
	  inCNV.resize(numBins);
	  memset(&inCNV[0], 0, numBins);
	  const vector < pair <int, int> > &CNVstartEnds = CNVs[IDstr].regions[chr0];
	  for (int k = 0; k < (int) CNVstartEnds.size(); k++)
	    memset(&inCNV[CNVstartEnds[k].first / binSize], 1,
		   (CNVstartEnds[k].second - CNVstartEnds[k].first) / binSize);

	  // compute cumulative OBS and EXP
	  cumOBSexclCNV.resize(numBins+1); cumEXPexclCNV.resize(numBins+1); cumEXPexclCNVnoPC.resize(numBins+1);
	  cumOBSinclCNV.resize(numBins+1); cumEXPinclCNV.resize(numBins+1); cumEXPinclCNVnoPC.resize(numBins+1);
	  for (int b = 0; b < numBins; b++) {
	    cumOBSexclCNV[b+1] = cumOBSexclCNV[b] + (inCNV[b] ? 0 : readsPerBin[b]);
	    cumEXPexclCNV[b+1] = cumEXPexclCNV[b] + (inCNV[b] ? 0 : expPerBin[b]);
        cumEXPexclCNVnoPC[b+1] = cumEXPexclCNVnoPC[b] +  (inCNV[b] ? 0 : expPerBinNoPCadj[b]);
	    cumOBSinclCNV[b+1] = cumOBSinclCNV[b] + readsPerBin[b];
	    cumEXPinclCNV[b+1] = cumEXPinclCNV[b] + expPerBin[b];
        cumEXPinclCNVnoPC[b+1] = cumEXPinclCNVnoPC[b] +  expPerBinNoPCadj[b];
	  }

	  // process each query region
	  for (int r = 0; r < (int) regionsPerChr.regions[chr0].size(); r++) {
	    int start = regionsPerChr.regions[chr0][r].first;
	    int end = regionsPerChr.regions[chr0][r].second;
	    int bStart = (start+binSize-2)/binSize;
	    int bEnd = min(end/binSize, numBins);

	    double OBSexclCNV = cumOBSexclCNV[bEnd]-cumOBSexclCNV[bStart];
	    double EXPexclCNV = cumEXPexclCNV[bEnd]-cumEXPexclCNV[bStart];
        double EXPexclCNVnoPC = cumEXPexclCNVnoPC[bEnd]-cumEXPexclCNVnoPC[bStart];
	    double OBSinclCNV = cumOBSinclCNV[bEnd]-cumOBSinclCNV[bStart];
	    double EXPinclCNV = cumEXPinclCNV[bEnd]-cumEXPinclCNV[bStart];
        double EXPinclCNVnoPC = cumEXPinclCNVnoPC[bEnd]-cumEXPinclCNVnoPC[bStart];

	    double relDepthExclCNV = OBSexclCNV / EXPexclCNV;
	    double relDepthInclCNV = OBSinclCNV / EXPinclCNV;
	    double fracInCNV = 1 - EXPexclCNV / EXPinclCNV;
	    double depthInCNVvsNotCNV = (OBSinclCNV-OBSexclCNV)/(EXPinclCNV-EXPexclCNV)
	      / relDepthExclCNV;
	      
	    // compute relative depth (unmasking CNV calls if depth suggests they were mosaic)
	    double relDepth = relDepthExclCNV, relDepthSE = sqrt(OBSexclCNV) / EXPexclCNV;
	    if (isnan(relDepthExclCNV) ||
		(fabs(relDepthExclCNV-1) > 0.05 && fracInCNV > 0.25 && 
		 fabs(depthInCNVvsNotCNV-1) < 0.4) ||
		(fracInCNV > 0.5 && 0.6 < depthInCNVvsNotCNV && depthInCNVvsNotCNV < 1)) {
	      relDepth = relDepthInclCNV;
	      relDepthSE = sqrt(OBSinclCNV) / EXPinclCNV;
	    }

	    // compute absolute depth deviation
	    double depthDev = relDepth - 1, depthDevSE = relDepthSE;
	    if (chr0==24-1 || (chr0==23-1 && sex==1)) { // adjust for ploidy if 1 rather than 2
	      depthDev *= 0.5;
	      depthDevSE *= 0.5;
	    }
	      
	    // write output line
	    fout << IDstr << "\t" << chr0toString(chr0) << "\t" << start << "\t" << end << "\t"
		 << depthDev << "\t" << depthDevSE << "\t"
		 << relDepthExclCNV << "\t" << relDepthInclCNV << "\t" << fracInCNV << "\t"
         << OBSinclCNV << "\t" << EXPinclCNV << "\t" << EXPinclCNVnoPC << "\t" 
         << OBSexclCNV << "\t" << EXPexclCNV << "\t" << EXPexclCNVnoPC << endl;

	    // write bin-level data
	    if (writeBinLevelOutput) {
	      string chrStr = chr0toString(chr0);
	      for (int b = bStart; b < bEnd; b++) 
		  foutBinLevel << IDstr << "\t" << chrStr << ":" << start << "-" << end << "\t"
			     << b*binSize << "\t" << (b+1)*binSize << "\t"
			     << readsPerBin[b] << "\t" << expPerBin[b] << "\t" << expPerBinNoPCadj[b] << "\t"
			     << readsPerBin[b]/expPerBin[b] << "\t" << (inCNV[b] ? 1 : 0) << endl;
	    }
	  }
	}
      }
      bgzf_close(finCounts);
    }
    ks_free(&kstr);
    bgzf_close(finDepthProfile);
    cerr << "Analyzed " << ctrIDregionsAnalyzed << " (ID, region) pairs for " << ctrIDsAnalyzed
	 << " unique samples" << endl;
  }

  fout.close();
  foutBinLevel.close();
  
  gettimeofday(&tv, NULL); double tCur = tv.tv_sec + tv.tv_usec*1e-6;
  cerr << "Time: " << tCur-tPrev << " sec" << endl;

  return 0;
}
