// g++ -O3 -Wall GenerateRefMasks.cpp -o generateRefMasks
// ./generateRefMasks /n/data1/bwh/medicine/loh/ploh/research/WGSnorm/read_weight/Homo_sapiens_assembly38/Homo_sapiens_assembly38 5 GRCh38.GCmasks.bin | tee GRCh38.GCmasks.log


#include <vector>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cassert>

#include "RefMasks.hpp"

using namespace std;

int main(int argc, char *argv[]){

  if (argc != 4) {
    fprintf(stderr, "Usage:\n");
    fprintf(stderr, "- arg1: reference metadata bundle prefix -> .fasta, .{gc,lc,sv,cnv}mask.fasta\n");
    fprintf(stderr, "- arg2: bit shift (e.g., 5 to downsample to 32bp bins)\n");
    fprintf(stderr, "- arg3: output binary file\n");
    exit(1);
  }

  const char *metadata_prefix = argv[1];
  int shift; sscanf(argv[2], "%d", &shift);
  const char *out_prefix = argv[3];

  printf("Using bit shift = %d to downsample to %dbp bins\n", shift, 1<<shift);

  const char metadata_suffixes[5][20] = {"fasta", "gcmask.fasta", "lcmask.fasta", "svmask.fasta",
					 "cnvmask.fasta"}; // generated by /n/data1/bwh/medicine/loh/ploh/research/GSnorm/cnvmask/make_cnvmask.sh

  // arrays for string storage
  const int BUF_SIZE = 100000;
  char buf[BUF_SIZE], buf2[BUF_SIZE]; buf[BUF_SIZE-1] = '\0';

  // open reference and mask files
  FILE *fin[5]; // ref, gcmask, lcmask, svmask
  for (int f = 0; f < 5; f++) {
    sprintf(buf, "%s.%s", metadata_prefix, metadata_suffixes[f]);
    printf("Opening metadata file: %s\n", buf); fflush(stdout);
    fin[f] = fopen(buf, "r");
    assert(fin[f] != NULL);
  }

  // open output file
  FILE *fout = fopen(out_prefix, "wb");
  assert(fout != NULL);

  // create vectors to store output data
  vector <int> chrLens; // chromosome lengths
  vector < vector <uint16_t> > GCmasks;

  char GC_status[GC_WINDOW];
  int GC_count = 0;
  int ref_pos0 = -1, prev_mask_pos0[5] = {-1, -1, -1, -1, -1};
  int ctrGCstringent = 0, ctrLCSVCNV = 0, ctrLCSV = 0, ctrLConly = 0;

  while (1) { // iterate through fastas
    // get next base of ref fasta
    int base;
    do { 
      base = fgetc(fin[0]); assert(base!=EOF);
    } while (base=='\n');

    if (chrLens.empty()) assert(base=='>'); // require first character to be '>'

    if (base=='>') {
      // report masks statistics for previous chromosome
      if (!chrLens.empty()) {
	printf("Number of downsampled segments:          %9d\n", (int) GCmasks.back().size());
	printf("Number of segments for GC profile:       %9d\n", ctrGCstringent);
	printf("Number of segments passing LC+SV+CNV:    %9d\n", ctrLCSVCNV);
	printf("Number of segments passing LC+SV masks:  %9d\n", ctrLCSV);
	printf("Number of segments passing LC mask:      %9d\n", ctrLConly);
      }

      // process next contig from ref fasta
      fscanf(fin[0], "%s", buf); // read contig name
      if (strcmp(buf, "chrM")==0) // stop at chrM
	break;
      printf("Processing contig %s: ", buf); fflush(stdout);

      // check agreement with mask fastas
      for (int f = 1; f < 5; f++) {
	fscanf(fin[f], "%s", buf2);
	assert(buf2[0]=='>' && strcmp(buf, buf2+1) == 0); // contig names must agree
      }

      // read next 3 fields from ref fasta; 4th field is length
      assert(fscanf(fin[0], " AC:%s", buf) == 1);
      assert(fscanf(fin[0], " gi:%s", buf) == 1);
      int len;
      assert(fscanf(fin[0], " LN:%d", &len) == 1);
      printf(" length = %d\n", len);
      
      // create new GCmasks vector for next chromosome
      chrLens.push_back(len);
      GCmasks.push_back(vector <uint16_t> ((len+(1<<shift)-1)>>shift));

      // throw away rest of line
      for (int f = 0; f < 5; f++) {
	assert(fgets(buf, BUF_SIZE-1, fin[f]) != NULL);
	assert(strlen(buf) < BUF_SIZE-1);
      }

      // initialize variables for keeping track of bases/masks for chromosome
      memset(GC_status, 0, GC_WINDOW);
      GC_count = 0;
      ref_pos0 = -1; // reset reference counter; htslib uses 0-indexing
      for (int f = 0; f < 5; f++) prev_mask_pos0[f] = -1;
      ctrGCstringent = ctrLCSVCNV = ctrLCSV = ctrLConly = 0;
      
      continue;
    }

    // advance 0-based position in ref fasta
    ref_pos0++;

    // get next character of each mask fasta
    for (int f = 1; f < 5; f++) {
      int base_mask;
      do {
	base_mask = fgetc(fin[f]); assert(base_mask!=EOF);
      } while (base_mask=='\n');
      //assert(base_mask == '0' || base_mask == '1');
      if (base_mask == '1')
	prev_mask_pos0[f] = ref_pos0;
    }

    // update GC_count; update last N base in ref fasta if necessary
    GC_count -= GC_status[ref_pos0 % GC_WINDOW];

    switch (base) {
    case 'G':
    case 'C':
      GC_status[ref_pos0 % GC_WINDOW]=1; break;
    case 'A':
    case 'T':
      GC_status[ref_pos0 % GC_WINDOW]=0; break;
    default: // bad base
      GC_status[ref_pos0 % GC_WINDOW]=0;
      prev_mask_pos0[0] = ref_pos0;
    }

    GC_count += GC_status[ref_pos0 % GC_WINDOW];

    // check if current position is GC_WINDOW/2 bp after a downsampling point: if so, set GC value
    if (ref_pos0 >= GC_WINDOW/2 && ((ref_pos0 - GC_WINDOW/2) & ((1<<shift)-1)) == 0) {
      GCmasks.back()[(ref_pos0 - GC_WINDOW/2)>>shift] |= GC_count;
      /*
      printf("set GCmasks at %d to %d [GC=%d]\n", ref_pos0 - GC_WINDOW/2,
	     GCmasks.back()[(ref_pos0 - GC_WINDOW/2)>>shift], GC_count);
      */
    }
    // check if current position is at end of a downsampling interval: if so, set masks
    if (((ref_pos0+1) & ((1<<shift)-1)) == 0) {
      uint16_t masks =
	(ref_pos0 < prev_mask_pos0[1] + (1<<shift) ? GCMASK_AT_SEG : 0) |
	(ref_pos0 < prev_mask_pos0[2] + (1<<shift) ? LCMASK_AT_SEG : 0) |
	(ref_pos0 < prev_mask_pos0[3] + (1<<shift) ? SVMASK_AT_SEG : 0) |
	(ref_pos0 < prev_mask_pos0[4] + (1<<shift) ? CNVMASK_AT_SEG : 0) |
	(ref_pos0 < prev_mask_pos0[0] + GC_WINDOW ? REFMASK_IN_WINDOW : 0);
      GCmasks.back()[ref_pos0>>shift] |= masks;
      if (!(masks & (REFMASK_IN_WINDOW|GCMASK_AT_SEG|LCMASK_AT_SEG|SVMASK_AT_SEG|CNVMASK_AT_SEG)))
	ctrGCstringent++;
      if (!(masks & (REFMASK_IN_WINDOW|LCMASK_AT_SEG|SVMASK_AT_SEG|CNVMASK_AT_SEG)))
	ctrLCSVCNV++;
      if (!(masks & (REFMASK_IN_WINDOW|LCMASK_AT_SEG|SVMASK_AT_SEG)))
	ctrLCSV++;
      if (!(masks & (REFMASK_IN_WINDOW|LCMASK_AT_SEG)))
	ctrLConly++;
      //printf("set masks ending at %d to %d\n", ref_pos0, GCmasks.back()[ref_pos0>>shift]);
    }
  }

  for (int f = 0; f < 5; f++)
    fclose(fin[f]);

  assert(chrLens.size() == NUM_CHROMS); // should have processed chr1-22,X,Y

  fwrite(&shift, sizeof(shift), 1, fout); // bit shift
  fwrite(&chrLens[0], sizeof(chrLens[0]), NUM_CHROMS, fout); // chromosome lengths
  for (int i = 0; i < NUM_CHROMS; i++)
    fwrite(&GCmasks[i][0], sizeof(GCmasks[i][0]), GCmasks[i].size(), fout); // GCmasks vectors

  fclose(fout);

  return 0;
}
